name `MirageStoreSetItem` columns 2 through 10
xivdev/EXDSchema pull request #51
Opened 2024-12-03 01:09 UTC by ArcaneDisgea

Using Boilmaster [response](https://beta.xivapi.com/api/1/sheet/MirageStoreSetItem/45156) as an example, `MirageStoreSetItem` key `45156`, `the emperor's new attire`.
```json
{
  "schema": "exdschema@48db4b87e3afd753676f96a804d06a97347cc11d-2024.11.06.0000.0000",
  "row_id": 45156,
  "fields": {
    "Unknown0": 0,
    "Unknown1": 0,
    "Unknown2": 10032,
    "Unknown3": 10033,
    "Unknown4": 10034,
    "Unknown5": 10035,
    "Unknown6": 10036,
    "Unknown7": 9293,
    "Unknown8": 9292,
    "Unknown9": 9294,
    "Unknown10": 9295
  }
}
```

[Querying](https://beta.xivapi.com/api/1/sheet/Item?rows=10032,10033,10034,10035,10036,9293,9292,9294&fields=Name,EquipSlotCategory) for each item shows their associated ItemUICategory. Column name holds true through the entire sheet.

```json
{
  "schema": "exdschema@48db4b87e3afd753676f96a804d06a97347cc11d-2024.11.06.0000.0000",
  "rows": [
    {
      "row_id": 10032,
      "fields": {
        "ItemUICategory": {
          "value": 34,
          "sheet": "ItemUICategory",
          "row_id": 34,
          "fields": {
            "Name": "Head"
          }
        },
        "Name": "The Emperor's New Hat"
      }
    },
    {
      "row_id": 10033,
      "fields": {
        "ItemUICategory": {
          "value": 35,
          "sheet": "ItemUICategory",
          "row_id": 35,
          "fields": {
            "Name": "Body"
          }
        },
        "Name": "The Emperor's New Robe"
      }
    },
    {
      "row_id": 10034,
      "fields": {
        "ItemUICategory": {
          "value": 37,
          "sheet": "ItemUICategory",
          "row_id": 37,
          "fields": {
            "Name": "Hands"
          }
        },
        "Name": "The Emperor's New Gloves"
      }
    },
    {
      "row_id": 10035,
      "fields": {
        "ItemUICategory": {
          "value": 36,
          "sheet": "ItemUICategory",
          "row_id": 36,
          "fields": {
            "Name": "Legs"
          }
        },
        "Name": "The Emperor's New Breeches"
      }
    },
    {
      "row_id": 10036,
      "fields": {
        "ItemUICategory": {
          "value": 38,
          "sheet": "ItemUICategory",
          "row_id": 38,
          "fields": {
            "Name": "Feet"
          }
        },
        "Name": "The Emperor's New Boots"
      }
    },
    {
      "row_id": 9293,
      "fields": {
        "ItemUICategory": {
          "value": 41,
          "sheet": "ItemUICategory",
          "row_id": 41,
          "fields": {
            "Name": "Earrings"
          }
        },
        "Name": "The Emperor's New Earrings"
      }
    },
    {
      "row_id": 9292,
      "fields": {
        "ItemUICategory": {
          "value": 40,
          "sheet": "ItemUICategory",
          "row_id": 40,
          "fields": {
            "Name": "Necklace"
          }
        },
        "Name": "The Emperor's New Necklace"
      }
    },
    {
      "row_id": 9294,
      "fields": {
        "ItemUICategory": {
          "value": 42,
          "sheet": "ItemUICategory",
          "row_id": 42,
          "fields": {
            "Name": "Bracelets"
          }
        },
        "Name": "The Emperor's New Bracelet"
      }
    }
  ]
}
```

Of note `Unknown0` and `Unknown1` are just `0` straight through the entire sheet. I would assume it's mainhand/offhand and they are giving themselves that space rather than adding new columns later but until they actually add something to confirm that I wouldn't be comfortable naming those.

2024-12-16 13:24 UTC, ArcaneDisgea commented
> Try changing all of them to linked fields like so:
> 
> ```yaml
>   - name: Head
>     type: link
>     targets: [Item]
> ```
> 
> Also, would it be more beneficial to do this via an array? I'm not sure if explicitly defining each column is a good idea.

Updated to linked fields.

With regards to an array, I think named fields are much better for consumers and an array in this context would be ambiguous and require each consumer to either refer to docs on what each entry applies to or redo the legwork to find each entry. I think that work should be centralized by the schema rather than every consumer getting surprised in the event of a column shift and all having to do the same work over again.

Additionally the rows can be quite sparse in some cases ( swimsuit outfits only having two or three of the nine possible pieces ) meaning there would be a plethora of `0` or empty values in many rows.

2024-12-20 15:52 UTC, mattantonelli commented
These column names are correct, but I'm not sure what the benefit is. Can you provide a use case?

For my use case, I'm going to be storing a list of items associated with an outfit. The equipment slot is not consequential in the context of the glamour dresser. But if I wanted it, I could always refer to the data on the Item itself.

2025-01-17 16:40 UTC, Haselnussbomber requested changes

2025-01-17 16:40 UTC, Haselnussbomber commented on Schemas/2024.11.06.0000.0000/MirageStoreSetItem.yml
>    - name: Unknown1
The game checks the EquipSlotCategory columns along with the MirageStoreSetItem columns with the same array index, in the function that is called here `E8 ?? ?? ?? ?? 85 C0 74 56 48 8B 0D`:
![Screenshot](https://github.com/user-attachments/assets/a62c52c2-bb82-4d93-8c28-4603f8cbf474)

So column 0 and 1 are MainHand and OffHand, respectively:

```suggestion
  - name: MainHand
    type: link
    targets: [Item]
  - name: OffHand
    type: link
    targets: [Item]
```

2025-01-17 16:44 UTC, ArcaneDisgea commented on Schemas/2024.11.06.0000.0000/MirageStoreSetItem.yml
>    - name: Unknown1
That's what I figured but I didn't have anything concrete when I looked at the sheet so I didn't want to name them. Thanks for confirming this!

2025-03-24 18:18 UTC, merged